# Generated by Django 4.2.11 on 2026-05-19 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anonymizer_app', '0008_restoredresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('draft', '作成済み'), ('sent_to_dmz', 'DMZ送信済み'), ('imported_to_open', 'OpenSide取込済み')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='restoredresult',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoredresult',
            name='status',
            field=models.CharField(choices=[('imported', '取込済み'), ('deleted', '削除済み')], default='imported', max_length=32),
        ),
        migrations.AddField(
            model_name='restoremetadata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoremetadata',
            name='status',
            field=models.CharField(choices=[('draft', '作成済み'), ('sent_to_dmz', 'DMZ送信済み'), ('imported_to_open', 'OpenSide取込済み'), ('returned_to_dmz', '返却DMZ送信済み'), ('imported_to_close', 'CloseSide取込済み')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
