# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0011_prompt_source_input_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInputDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('default_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'field_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='templateinputdefault',
            constraint=models.UniqueConstraint(fields=('template_type', 'field_key'), name='unique_template_input_default'),
        ),
    ]
