# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0012_templateinputdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinputdefault',
            name='required_override',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
