# Generated by Django 4.2.11 on 2026-05-22 23:14

from django.db import migrations, models
import django.db.models.deletion


def seed_checkbox_group_defaults(apps, schema_editor):
    TemplateInputCheckboxGroup = apps.get_model('anonymizer_app', 'TemplateInputCheckboxGroup')
    TemplateInputCheckboxOption = apps.get_model('anonymizer_app', 'TemplateInputCheckboxOption')

    option_texts = [
        '安静',
        '輸液',
        '食事制限',
        '薬剤調整',
        '抗菌薬投与',
        '酸素投与',
        '検査・経過観察',
        '処置・手術',
        'リハビリ',
        '退院・転院調整',
    ]

    group, _created = TemplateInputCheckboxGroup.objects.get_or_create(
        template_type='入院時サマリー',
        field_key='treatment_plan',
    )
    for index, text in enumerate(option_texts):
        option, created = TemplateInputCheckboxOption.objects.get_or_create(
            group=group,
            text=text,
            defaults={'sort_order': index * 10},
        )
        if not created and option.sort_order != index * 10:
            option.sort_order = index * 10
            option.save(update_fields=['sort_order', 'updated_at'])


def unseed_checkbox_group_defaults(apps, schema_editor):
    TemplateInputCheckboxGroup = apps.get_model('anonymizer_app', 'TemplateInputCheckboxGroup')
    TemplateInputCheckboxGroup.objects.filter(
        template_type='入院時サマリー',
        field_key='treatment_plan',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0013_templateinputdefault_required_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInputCheckboxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='TemplateInputCheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='anonymizer_app.templateinputcheckboxgroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='templateinputcheckboxgroup',
            constraint=models.UniqueConstraint(fields=('template_type', 'field_key'), name='unique_template_input_checkbox_group'),
        ),
        migrations.AddConstraint(
            model_name='templateinputcheckboxoption',
            constraint=models.UniqueConstraint(fields=('group', 'text'), name='unique_template_input_checkbox_option'),
        ),
        migrations.RunPython(seed_checkbox_group_defaults, reverse_code=unseed_checkbox_group_defaults),
    ]
