# Generated by Django 6.0.5 on 2026-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0014_template_checkbox_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('精神科入院時サマリー', '精神科入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255),
        ),
        migrations.AlterField(
            model_name='templateinputcheckboxgroup',
            name='template_type',
            field=models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('精神科入院時サマリー', '精神科入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255),
        ),
        migrations.AlterField(
            model_name='templateinputdefault',
            name='template_type',
            field=models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('精神科入院時サマリー', '精神科入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255),
        ),
    ]
