# Generated by Django 6.0.5 on 2026-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0017_alter_template_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinputfield',
            name='textarea_rows',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
