# Generated by Codex on 2026-05-29

import django.utils.timezone
from django.db import migrations, models


def populate_template_sort_order_and_active(apps, schema_editor):
    Template = apps.get_model('anonymizer_app', 'Template')

    from anonymizer_app.prompt_template_store import list_template_sources

    source_filenames = [source.source_filename for source in list_template_sources()]
    order_map = {filename: index for index, filename in enumerate(source_filenames)}
    templates = list(Template.objects.all())
    templates.sort(
        key=lambda template: (
            0 if template.source_filename in order_map else 1,
            order_map.get(template.source_filename, 10**9),
            template.source_filename or '',
            template.pk,
        )
    )

    now = django.utils.timezone.now()
    for index, template in enumerate(templates, start=1):
        template.sort_order = index
        template.is_active = True
        template.updated_at = now

    if templates:
        Template.objects.bulk_update(templates, ['sort_order', 'is_active', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0021_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['sort_order', 'template_type', 'name', 'id']},
        ),
        migrations.RunPython(populate_template_sort_order_and_active, migrations.RunPython.noop),
    ]
