# Generated by Django 4.2.11 on 2026-09-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('permission_level', models.PositiveIntegerField(default=1)),
                ('input_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=160, max_digits=10)),
                ('cost_jpy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失敗'), ('REJECTED_LIMIT', '制限拒否'), ('TIMEOUT', 'タイムアウト')], max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal_ai.modelsetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', '一般職員'), ('ADMIN', '管理者'), ('SUPER_ADMIN', '最高管理者')], default='USER', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('daily_request_limit', models.PositiveIntegerField(default=50)),
                ('monthly_cost_limit_jpy', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('max_input_chars', models.PositiveIntegerField(default=20000)),
                ('max_output_tokens', models.PositiveIntegerField(default=2000)),
                ('allowed_model_level', models.PositiveIntegerField(default=1)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
