# Generated by Django 6.0.5 on 2026-05-18 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0002_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
