# Generated by Django 4.2.11 on 2026-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0009_prompt_owner_prompt_source_id_prompt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='import_source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='result',
            field=models.CharField(choices=[('success', '成功'), ('failure', '失敗')], default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
