# Generated by Django 4.2.11 on 2026-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0010_operationlog_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='source_input_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
