# Generated by Django 6.0.5 on 2026-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0015_add_psychiatric_admission_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('入院時サマリー', '入院時サマリー'), ('精神科入院時サマリー', '精神科入院時サマリー'), ('退院時サマリー', '退院時サマリー'), ('中間サマリー', '中間サマリー'), ('インシデントレポート', 'インシデントレポート'), ('委員会議事録', '委員会議事録'), ('看護計画', '看護計画')], max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('input_type', models.CharField(choices=[('textarea', 'テキスト'), ('checkbox_group', 'チェックボックス')], default='textarea', max_length=32)),
                ('section_title', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('allow_other', models.BooleanField(default=True)),
                ('other_label', models.CharField(blank=True, default='その他', max_length=255)),
                ('other_placeholder', models.CharField(blank=True, default='自由入力', max_length=255)),
                ('help_text', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'sort_order', 'field_key'],
                'constraints': [models.UniqueConstraint(fields=('template_type', 'field_key'), name='unique_template_input_field')],
            },
        ),
    ]
