# Generated by Django 6.0.5 on 2026-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0019_alter_template_template_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinputfield',
            name='input_type',
            field=models.CharField(choices=[('textarea', 'テキスト'), ('date', '日付'), ('checkbox_group', 'チェックボックス')], default='textarea', max_length=32),
        ),
    ]
