# Generated by Django 4.2.11 on 2026-05-24 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0020_alter_templateinputfield_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('kana_surname', models.CharField(blank=True, default='', max_length=255)),
                ('kana_given_name', models.CharField(blank=True, default='', max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', 'その他'), ('unknown', '不明')], default='', max_length=16)),
                ('primary_diagnosis', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
    ]
