# Generated by Codex on 2026-07-04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0022_template_sort_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('kana_surname', models.CharField(blank=True, default='', max_length=255)),
                ('kana_given_name', models.CharField(blank=True, default='', max_length=255)),
                ('role_label', models.CharField(blank=True, default='職員', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
    ]
