# Generated by Codex on 2026-07-04

import django.utils.timezone
from django.db import migrations, models


def copy_staff_role_label_to_occupation(apps, schema_editor):
    Staff = apps.get_model('anonymizer_app', 'Staff')
    for staff in Staff.objects.all():
        occupation_label = str(getattr(staff, 'occupation_label', '') or '').strip()
        role_label = str(getattr(staff, 'role_label', '') or '').strip()
        position_label = str(getattr(staff, 'position_label', '') or '').strip()
        updated_fields = []
        if not occupation_label and role_label:
            staff.occupation_label = role_label
            updated_fields.append('occupation_label')
        if not role_label and occupation_label:
            staff.role_label = occupation_label
            updated_fields.append('role_label')
        if not position_label and not getattr(staff, 'position_label', None):
            staff.position_label = ''
            updated_fields.append('position_label')
        if updated_fields:
            staff.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0023_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='occupation_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PatientFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=255)),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('kana_surname', models.CharField(blank=True, default='', max_length=255)),
                ('kana_given_name', models.CharField(blank=True, default='', max_length=255)),
                ('relationship_label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id', 'relationship_label', 'family_id'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=255)),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('kana_surname', models.CharField(blank=True, default='', max_length=255)),
                ('kana_given_name', models.CharField(blank=True, default='', max_length=255)),
                ('relationship_label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id', 'relationship_label', 'guardian_id'],
            },
        ),
        migrations.RunPython(copy_staff_role_label_to_occupation, migrations.RunPython.noop),
    ]
