# Generated by Codex on 2026-07-04

import re
from collections import defaultdict

from django.db import migrations, models


def populate_branch_no_from_legacy_ids(apps, schema_editor):
    def _populate(model_name: str, legacy_field_name: str):
        Model = apps.get_model('anonymizer_app', model_name)
        records = list(Model.objects.all().order_by('patient_id', 'created_at', 'id'))
        used_branch_nos = defaultdict(set)
        next_branch_nos = defaultdict(int)

        for record in records:
            patient_id = str(getattr(record, 'patient_id', '') or '').strip()
            legacy_id = str(getattr(record, legacy_field_name, '') or '').strip()

            branch_no = None
            match = re.search(r'(\d+)$', legacy_id)
            if match:
                branch_no = int(match.group(1))

            if not branch_no or branch_no <= 0 or branch_no in used_branch_nos[patient_id]:
                branch_no = next_branch_nos[patient_id] + 1
                while branch_no in used_branch_nos[patient_id]:
                    branch_no += 1

            used_branch_nos[patient_id].add(branch_no)
            next_branch_nos[patient_id] = max(next_branch_nos[patient_id], branch_no)
            record.branch_no = branch_no
            record.save(update_fields=['branch_no'])

    _populate('PatientFamily', 'family_id')
    _populate('Guardian', 'guardian_id')


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0024_staff_person_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfamily',
            name='branch_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='枝番'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='branch_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='枝番'),
        ),
        migrations.RunPython(populate_branch_no_from_legacy_ids, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='patientfamily',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='guardian_id',
        ),
        migrations.AlterField(
            model_name='patientfamily',
            name='branch_no',
            field=models.PositiveIntegerField(db_index=True, verbose_name='枝番'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='branch_no',
            field=models.PositiveIntegerField(db_index=True, verbose_name='枝番'),
        ),
        migrations.AlterModelOptions(
            name='patientfamily',
            options={'ordering': ['patient_id', 'branch_no']},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['patient_id', 'branch_no']},
        ),
        migrations.AddConstraint(
            model_name='patientfamily',
            constraint=models.UniqueConstraint(fields=('patient_id', 'branch_no'), name='unique_patient_family_branch_no'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(fields=('patient_id', 'branch_no'), name='unique_patient_guardian_branch_no'),
        ),
    ]
