# Generated by Codex on 2026-07-04

from collections import defaultdict

from django.db import migrations, models
from django.utils import timezone


def populate_patient_linked_persons(apps, schema_editor):
    PatientLinkedPerson = apps.get_model('anonymizer_app', 'PatientLinkedPerson')
    PatientFamily = apps.get_model('anonymizer_app', 'PatientFamily')
    Guardian = apps.get_model('anonymizer_app', 'Guardian')

    used_branch_nos = defaultdict(set)

    def allocate_branch_no(patient_id: str, preferred_branch_no: int | None) -> int:
        patient_key = str(patient_id or '').strip()
        preferred_branch_no = int(preferred_branch_no or 0)
        if preferred_branch_no > 0 and preferred_branch_no not in used_branch_nos[patient_key]:
            used_branch_nos[patient_key].add(preferred_branch_no)
            return preferred_branch_no

        branch_no = 1
        while branch_no in used_branch_nos[patient_key]:
            branch_no += 1
        used_branch_nos[patient_key].add(branch_no)
        return branch_no

    def copy_records(source_model, relation_kind: str):
        for source in source_model.objects.all().order_by('patient_id', 'branch_no', 'created_at', 'id'):
            patient_id = str(getattr(source, 'patient_id', '') or '').strip()
            if not patient_id:
                continue

            branch_no = allocate_branch_no(patient_id, getattr(source, 'branch_no', None))
            linked_person = PatientLinkedPerson.objects.create(
                patient_id=patient_id,
                branch_no=branch_no,
                relation_kind=relation_kind,
                surname=str(getattr(source, 'surname', '') or ''),
                given_name=str(getattr(source, 'given_name', '') or ''),
                kana_surname=str(getattr(source, 'kana_surname', '') or ''),
                kana_given_name=str(getattr(source, 'kana_given_name', '') or ''),
                relationship_label=str(getattr(source, 'relationship_label', '') or ''),
                is_active=bool(getattr(source, 'is_active', True)),
                created_at=getattr(source, 'created_at', timezone.now()),
                updated_at=getattr(source, 'updated_at', timezone.now()),
            )
            PatientLinkedPerson.objects.filter(pk=linked_person.pk).update(
                created_at=getattr(source, 'created_at', timezone.now()),
                updated_at=getattr(source, 'updated_at', timezone.now()),
            )

    copy_records(PatientFamily, 'family')
    copy_records(Guardian, 'guardian')


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0025_patient_family_guardian_branch_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLinkedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=255)),
                ('branch_no', models.PositiveIntegerField(db_index=True, verbose_name='枝番')),
                ('relation_kind', models.CharField(choices=[('family', '家族'), ('guardian', '後見人')], db_index=True, default='family', max_length=16, verbose_name='種別')),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('kana_surname', models.CharField(blank=True, default='', max_length=255)),
                ('kana_given_name', models.CharField(blank=True, default='', max_length=255)),
                ('relationship_label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id', 'branch_no'],
            },
        ),
        migrations.RunPython(populate_patient_linked_persons, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='PatientFamily',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.AddConstraint(
            model_name='patientlinkedperson',
            constraint=models.UniqueConstraint(fields=('patient_id', 'branch_no'), name='unique_patient_linked_person_branch_no'),
        ),
    ]
