# Generated by Codex on 2026-07-04

from django.db import migrations, models


def populate_linked_person_codes(apps, _schema_editor):
    PatientLinkedPerson = apps.get_model('anonymizer_app', 'PatientLinkedPerson')
    for linked_person in PatientLinkedPerson.objects.all().order_by('id'):
        linked_person_code = f'LP{int(linked_person.pk):08d}'
        if getattr(linked_person, 'linked_person_code', None) == linked_person_code:
            continue
        PatientLinkedPerson.objects.filter(pk=linked_person.pk).update(linked_person_code=linked_person_code)


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer_app', '0026_patient_linked_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlinkedperson',
            name='linked_person_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True, verbose_name='個別コード'),
        ),
        migrations.RunPython(populate_linked_person_codes, migrations.RunPython.noop),
    ]
