# Generated by Django 6.0.5 on 2026-09-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_ai', '0003_seed_default_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='prompt_text',
            field=models.TextField(blank=True, null=True, verbose_name='質問本文'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='回答本文'),
        ),
    ]
