# Generated by Django 6.0.5 on 2026-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_ai', '0004_usagelog_prompt_text_usagelog_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='generated_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='image_cost_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
